services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: docs_collab_backend
    env_file: .env
    ports:
      - "1234:3000"
    restart: unless-stopped
